btnRegistreSe = "//*[@text='REGISTRE-SE']"
btnEntrar = "com.sharecare.realgreen:id/button_login"
btnVoceMoraNoBrasilSim = "//*[@text='SIM']"
btnAltereoPaisEmQueResideOK = "//*[@text='OK']"
btnCriar = "//*[@text='CRIAR']"
btnFechar = "android:id/button2"
btnProximo = "com.sharecare.realgreen:id/actionButton"
btnPermitir = "com.android.packageinstaller:id/permission_allow_button"
btnConfiguracoesSair = "//*[@text='Sair']"
btnSair = "//*[@text='SAIR']"

txtVoceMoraNoBrasilSim = "//*[@text='Você mora no Brasil?']"
txtCrieUmaConta = "//*[@text='Crie uma conta']"
txtInformeUmemailValido = "//*[@text='Informe um e-mail válido']"
txtInformeSuaSenha = "//*[@text='Informe sua senha']"
txtOcorreuUmErro = "//*[@text='Ocorreu um erro']"
txtEmailOuSenhaInvalidos = "//*[@text='E-mail ou senha inválidos']"

cpNome = "com.sharecare.realgreen:id/edit_text_first_name"
cpSobrenome = "com.sharecare.realgreen:id/edit_text_last_name"
cpEmail = "com.sharecare.realgreen:id/edit_text_email_address"
cpDataDeNascimento = "com.sharecare.realgreen:id/edit_text_birth_date"
cpCEP = "com.sharecare.realgreen:id/edit_text_zip_code"
cpSenha = "com.sharecare.realgreen:id/edit_text_password"
cpConfirmarSenha = "com.sharecare.realgreen:id/edit_text_confirm_password"
cpLoginEmail = "//*[@text='E-mail']"
cpLoginSenha = "//*[@text='Senha']"

cbSexoM = "com.sharecare.realgreen:id/radio_male"
cbSexoF = "com.sharecare.realgreen:id/radio_female"
cbEuConcordo = "com.sharecare.realgreen:id/accept_term_and_conditions"

lblPaginaInicial = "//*[@text='Página inicial']"
lblMonitore = "//*[@text='Monitore']"
lblDescubra = "//*[@text='Descubra']"
lblRealize = "//*[@text='Realize']"
lblVoce = "//*[@text='Você']"

iconConfiguracoes = "com.sharecare.realgreen:id/settings"